// Code generated by go-swagger; DO NOT EDIT.

package workflow_revisions

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"

	"github.com/puppetlabs/relay/pkg/client/api/models"
)

// GetWorkflowRevisionReader is a Reader for the GetWorkflowRevision structure.
type GetWorkflowRevisionReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetWorkflowRevisionReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetWorkflowRevisionOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewGetWorkflowRevisionDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewGetWorkflowRevisionOK creates a GetWorkflowRevisionOK with default headers values
func NewGetWorkflowRevisionOK() *GetWorkflowRevisionOK {
	return &GetWorkflowRevisionOK{}
}

/*GetWorkflowRevisionOK handles this case with default header values.

The retrieved workflow revision
*/
type GetWorkflowRevisionOK struct {
	Payload *GetWorkflowRevisionOKBody
}

func (o *GetWorkflowRevisionOK) Error() string {
	return fmt.Sprintf("[GET /api/workflows/{workflowName}/revisions/{workflowRevision}][%d] getWorkflowRevisionOK  %+v", 200, o.Payload)
}

func (o *GetWorkflowRevisionOK) GetPayload() *GetWorkflowRevisionOKBody {
	return o.Payload
}

func (o *GetWorkflowRevisionOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(GetWorkflowRevisionOKBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetWorkflowRevisionDefault creates a GetWorkflowRevisionDefault with default headers values
func NewGetWorkflowRevisionDefault(code int) *GetWorkflowRevisionDefault {
	return &GetWorkflowRevisionDefault{
		_statusCode: code,
	}
}

/*GetWorkflowRevisionDefault handles this case with default header values.

An error occurred
*/
type GetWorkflowRevisionDefault struct {
	_statusCode int

	Payload *GetWorkflowRevisionDefaultBody
}

// Code gets the status code for the get workflow revision default response
func (o *GetWorkflowRevisionDefault) Code() int {
	return o._statusCode
}

func (o *GetWorkflowRevisionDefault) Error() string {
	return fmt.Sprintf("[GET /api/workflows/{workflowName}/revisions/{workflowRevision}][%d] getWorkflowRevision default  %+v", o._statusCode, o.Payload)
}

func (o *GetWorkflowRevisionDefault) GetPayload() *GetWorkflowRevisionDefaultBody {
	return o.Payload
}

func (o *GetWorkflowRevisionDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(GetWorkflowRevisionDefaultBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

/*GetWorkflowRevisionDefaultBody Error response
swagger:model GetWorkflowRevisionDefaultBody
*/
type GetWorkflowRevisionDefaultBody struct {

	// error
	Error *models.Error `json:"error,omitempty"`
}

// Validate validates this get workflow revision default body
func (o *GetWorkflowRevisionDefaultBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateError(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *GetWorkflowRevisionDefaultBody) validateError(formats strfmt.Registry) error {

	if swag.IsZero(o.Error) { // not required
		return nil
	}

	if o.Error != nil {
		if err := o.Error.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("getWorkflowRevision default" + "." + "error")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (o *GetWorkflowRevisionDefaultBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *GetWorkflowRevisionDefaultBody) UnmarshalBinary(b []byte) error {
	var res GetWorkflowRevisionDefaultBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}

/*GetWorkflowRevisionOKBody get workflow revision o k body
swagger:model GetWorkflowRevisionOKBody
*/
type GetWorkflowRevisionOKBody struct {
	models.Entity

	// revision
	Revision *models.WorkflowRevision `json:"revision,omitempty"`
}

// UnmarshalJSON unmarshals this object from a JSON structure
func (o *GetWorkflowRevisionOKBody) UnmarshalJSON(raw []byte) error {
	// GetWorkflowRevisionOKBodyAO0
	var getWorkflowRevisionOKBodyAO0 models.Entity
	if err := swag.ReadJSON(raw, &getWorkflowRevisionOKBodyAO0); err != nil {
		return err
	}
	o.Entity = getWorkflowRevisionOKBodyAO0

	// GetWorkflowRevisionOKBodyAO1
	var dataGetWorkflowRevisionOKBodyAO1 struct {
		Revision *models.WorkflowRevision `json:"revision,omitempty"`
	}
	if err := swag.ReadJSON(raw, &dataGetWorkflowRevisionOKBodyAO1); err != nil {
		return err
	}

	o.Revision = dataGetWorkflowRevisionOKBodyAO1.Revision

	return nil
}

// MarshalJSON marshals this object to a JSON structure
func (o GetWorkflowRevisionOKBody) MarshalJSON() ([]byte, error) {
	_parts := make([][]byte, 0, 2)

	getWorkflowRevisionOKBodyAO0, err := swag.WriteJSON(o.Entity)
	if err != nil {
		return nil, err
	}
	_parts = append(_parts, getWorkflowRevisionOKBodyAO0)
	var dataGetWorkflowRevisionOKBodyAO1 struct {
		Revision *models.WorkflowRevision `json:"revision,omitempty"`
	}

	dataGetWorkflowRevisionOKBodyAO1.Revision = o.Revision

	jsonDataGetWorkflowRevisionOKBodyAO1, errGetWorkflowRevisionOKBodyAO1 := swag.WriteJSON(dataGetWorkflowRevisionOKBodyAO1)
	if errGetWorkflowRevisionOKBodyAO1 != nil {
		return nil, errGetWorkflowRevisionOKBodyAO1
	}
	_parts = append(_parts, jsonDataGetWorkflowRevisionOKBodyAO1)
	return swag.ConcatJSON(_parts...), nil
}

// Validate validates this get workflow revision o k body
func (o *GetWorkflowRevisionOKBody) Validate(formats strfmt.Registry) error {
	var res []error

	// validation for a type composition with models.Entity
	if err := o.Entity.Validate(formats); err != nil {
		res = append(res, err)
	}

	if err := o.validateRevision(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *GetWorkflowRevisionOKBody) validateRevision(formats strfmt.Registry) error {

	if swag.IsZero(o.Revision) { // not required
		return nil
	}

	if o.Revision != nil {
		if err := o.Revision.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("getWorkflowRevisionOK" + "." + "revision")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (o *GetWorkflowRevisionOKBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *GetWorkflowRevisionOKBody) UnmarshalBinary(b []byte) error {
	var res GetWorkflowRevisionOKBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
