// Code generated by go-swagger; DO NOT EDIT.

package workflow_revisions

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"

	"github.com/puppetlabs/nebula-cli/pkg/client/api/models"
)

// PostWorkflowRevisionReader is a Reader for the PostWorkflowRevision structure.
type PostWorkflowRevisionReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PostWorkflowRevisionReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 201:
		result := NewPostWorkflowRevisionCreated()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewPostWorkflowRevisionDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewPostWorkflowRevisionCreated creates a PostWorkflowRevisionCreated with default headers values
func NewPostWorkflowRevisionCreated() *PostWorkflowRevisionCreated {
	return &PostWorkflowRevisionCreated{}
}

/*PostWorkflowRevisionCreated handles this case with default header values.

The newly created workflow revision
*/
type PostWorkflowRevisionCreated struct {
	Payload *PostWorkflowRevisionCreatedBody
}

func (o *PostWorkflowRevisionCreated) Error() string {
	return fmt.Sprintf("[POST /api/workflows/{workflowName}/revisions][%d] postWorkflowRevisionCreated  %+v", 201, o.Payload)
}

func (o *PostWorkflowRevisionCreated) GetPayload() *PostWorkflowRevisionCreatedBody {
	return o.Payload
}

func (o *PostWorkflowRevisionCreated) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(PostWorkflowRevisionCreatedBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPostWorkflowRevisionDefault creates a PostWorkflowRevisionDefault with default headers values
func NewPostWorkflowRevisionDefault(code int) *PostWorkflowRevisionDefault {
	return &PostWorkflowRevisionDefault{
		_statusCode: code,
	}
}

/*PostWorkflowRevisionDefault handles this case with default header values.

An error occurred
*/
type PostWorkflowRevisionDefault struct {
	_statusCode int

	Payload *PostWorkflowRevisionDefaultBody
}

// Code gets the status code for the post workflow revision default response
func (o *PostWorkflowRevisionDefault) Code() int {
	return o._statusCode
}

func (o *PostWorkflowRevisionDefault) Error() string {
	return fmt.Sprintf("[POST /api/workflows/{workflowName}/revisions][%d] postWorkflowRevision default  %+v", o._statusCode, o.Payload)
}

func (o *PostWorkflowRevisionDefault) GetPayload() *PostWorkflowRevisionDefaultBody {
	return o.Payload
}

func (o *PostWorkflowRevisionDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(PostWorkflowRevisionDefaultBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

/*PostWorkflowRevisionCreatedBody post workflow revision created body
swagger:model PostWorkflowRevisionCreatedBody
*/
type PostWorkflowRevisionCreatedBody struct {
	models.Entity

	// revision
	Revision *models.WorkflowRevision `json:"revision,omitempty"`
}

// UnmarshalJSON unmarshals this object from a JSON structure
func (o *PostWorkflowRevisionCreatedBody) UnmarshalJSON(raw []byte) error {
	// PostWorkflowRevisionCreatedBodyAO0
	var postWorkflowRevisionCreatedBodyAO0 models.Entity
	if err := swag.ReadJSON(raw, &postWorkflowRevisionCreatedBodyAO0); err != nil {
		return err
	}
	o.Entity = postWorkflowRevisionCreatedBodyAO0

	// PostWorkflowRevisionCreatedBodyAO1
	var dataPostWorkflowRevisionCreatedBodyAO1 struct {
		Revision *models.WorkflowRevision `json:"revision,omitempty"`
	}
	if err := swag.ReadJSON(raw, &dataPostWorkflowRevisionCreatedBodyAO1); err != nil {
		return err
	}

	o.Revision = dataPostWorkflowRevisionCreatedBodyAO1.Revision

	return nil
}

// MarshalJSON marshals this object to a JSON structure
func (o PostWorkflowRevisionCreatedBody) MarshalJSON() ([]byte, error) {
	_parts := make([][]byte, 0, 2)

	postWorkflowRevisionCreatedBodyAO0, err := swag.WriteJSON(o.Entity)
	if err != nil {
		return nil, err
	}
	_parts = append(_parts, postWorkflowRevisionCreatedBodyAO0)
	var dataPostWorkflowRevisionCreatedBodyAO1 struct {
		Revision *models.WorkflowRevision `json:"revision,omitempty"`
	}

	dataPostWorkflowRevisionCreatedBodyAO1.Revision = o.Revision

	jsonDataPostWorkflowRevisionCreatedBodyAO1, errPostWorkflowRevisionCreatedBodyAO1 := swag.WriteJSON(dataPostWorkflowRevisionCreatedBodyAO1)
	if errPostWorkflowRevisionCreatedBodyAO1 != nil {
		return nil, errPostWorkflowRevisionCreatedBodyAO1
	}
	_parts = append(_parts, jsonDataPostWorkflowRevisionCreatedBodyAO1)
	return swag.ConcatJSON(_parts...), nil
}

// Validate validates this post workflow revision created body
func (o *PostWorkflowRevisionCreatedBody) Validate(formats strfmt.Registry) error {
	var res []error

	// validation for a type composition with models.Entity
	if err := o.Entity.Validate(formats); err != nil {
		res = append(res, err)
	}

	if err := o.validateRevision(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *PostWorkflowRevisionCreatedBody) validateRevision(formats strfmt.Registry) error {

	if swag.IsZero(o.Revision) { // not required
		return nil
	}

	if o.Revision != nil {
		if err := o.Revision.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("postWorkflowRevisionCreated" + "." + "revision")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (o *PostWorkflowRevisionCreatedBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *PostWorkflowRevisionCreatedBody) UnmarshalBinary(b []byte) error {
	var res PostWorkflowRevisionCreatedBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}

/*PostWorkflowRevisionDefaultBody Error response
swagger:model PostWorkflowRevisionDefaultBody
*/
type PostWorkflowRevisionDefaultBody struct {

	// error
	Error *models.Error `json:"error,omitempty"`
}

// Validate validates this post workflow revision default body
func (o *PostWorkflowRevisionDefaultBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateError(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *PostWorkflowRevisionDefaultBody) validateError(formats strfmt.Registry) error {

	if swag.IsZero(o.Error) { // not required
		return nil
	}

	if o.Error != nil {
		if err := o.Error.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("postWorkflowRevision default" + "." + "error")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (o *PostWorkflowRevisionDefaultBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *PostWorkflowRevisionDefaultBody) UnmarshalBinary(b []byte) error {
	var res PostWorkflowRevisionDefaultBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
