// Code generated by go-swagger; DO NOT EDIT.

package workflow_runs

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewGetWorkflowRunParams creates a new GetWorkflowRunParams object
// with the default values initialized.
func NewGetWorkflowRunParams() *GetWorkflowRunParams {
	var ()
	return &GetWorkflowRunParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetWorkflowRunParamsWithTimeout creates a new GetWorkflowRunParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetWorkflowRunParamsWithTimeout(timeout time.Duration) *GetWorkflowRunParams {
	var ()
	return &GetWorkflowRunParams{

		timeout: timeout,
	}
}

// NewGetWorkflowRunParamsWithContext creates a new GetWorkflowRunParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetWorkflowRunParamsWithContext(ctx context.Context) *GetWorkflowRunParams {
	var ()
	return &GetWorkflowRunParams{

		Context: ctx,
	}
}

// NewGetWorkflowRunParamsWithHTTPClient creates a new GetWorkflowRunParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetWorkflowRunParamsWithHTTPClient(client *http.Client) *GetWorkflowRunParams {
	var ()
	return &GetWorkflowRunParams{
		HTTPClient: client,
	}
}

/*GetWorkflowRunParams contains all the parameters to send to the API endpoint
for the get workflow run operation typically these are written to a http.Request
*/
type GetWorkflowRunParams struct {

	/*WorkflowName
	  Workflow name

	*/
	WorkflowName string
	/*WorkflowRunNumber
	  Run number of the associated workflow

	*/
	WorkflowRunNumber int64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get workflow run params
func (o *GetWorkflowRunParams) WithTimeout(timeout time.Duration) *GetWorkflowRunParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get workflow run params
func (o *GetWorkflowRunParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get workflow run params
func (o *GetWorkflowRunParams) WithContext(ctx context.Context) *GetWorkflowRunParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get workflow run params
func (o *GetWorkflowRunParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get workflow run params
func (o *GetWorkflowRunParams) WithHTTPClient(client *http.Client) *GetWorkflowRunParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get workflow run params
func (o *GetWorkflowRunParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithWorkflowName adds the workflowName to the get workflow run params
func (o *GetWorkflowRunParams) WithWorkflowName(workflowName string) *GetWorkflowRunParams {
	o.SetWorkflowName(workflowName)
	return o
}

// SetWorkflowName adds the workflowName to the get workflow run params
func (o *GetWorkflowRunParams) SetWorkflowName(workflowName string) {
	o.WorkflowName = workflowName
}

// WithWorkflowRunNumber adds the workflowRunNumber to the get workflow run params
func (o *GetWorkflowRunParams) WithWorkflowRunNumber(workflowRunNumber int64) *GetWorkflowRunParams {
	o.SetWorkflowRunNumber(workflowRunNumber)
	return o
}

// SetWorkflowRunNumber adds the workflowRunNumber to the get workflow run params
func (o *GetWorkflowRunParams) SetWorkflowRunNumber(workflowRunNumber int64) {
	o.WorkflowRunNumber = workflowRunNumber
}

// WriteToRequest writes these params to a swagger request
func (o *GetWorkflowRunParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param workflowName
	if err := r.SetPathParam("workflowName", o.WorkflowName); err != nil {
		return err
	}

	// path param workflowRunNumber
	if err := r.SetPathParam("workflowRunNumber", swag.FormatInt64(o.WorkflowRunNumber)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
