// Code generated by go-swagger; DO NOT EDIT.

package integrations_v1

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/puppetlabs/nebula/pkg/client/api/models"
)

// DeleteIntegrationReader is a Reader for the DeleteIntegration structure.
type DeleteIntegrationReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeleteIntegrationReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewDeleteIntegrationOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewDeleteIntegrationOK creates a DeleteIntegrationOK with default headers values
func NewDeleteIntegrationOK() *DeleteIntegrationOK {
	return &DeleteIntegrationOK{}
}

/*DeleteIntegrationOK handles this case with default header values.

Deletion successful
*/
type DeleteIntegrationOK struct {
	Payload *models.DeleteResponse
}

func (o *DeleteIntegrationOK) Error() string {
	return fmt.Sprintf("[DELETE /api/integrations/{id}][%d] deleteIntegrationOK  %+v", 200, o.Payload)
}

func (o *DeleteIntegrationOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.DeleteResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
