// Code generated by go-swagger; DO NOT EDIT.

package integrations_v1

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/puppetlabs/nebula/pkg/client/api/models"
)

// RedirectIntegrationReader is a Reader for the RedirectIntegration structure.
type RedirectIntegrationReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *RedirectIntegrationReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewRedirectIntegrationOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewRedirectIntegrationOK creates a RedirectIntegrationOK with default headers values
func NewRedirectIntegrationOK() *RedirectIntegrationOK {
	return &RedirectIntegrationOK{}
}

/*RedirectIntegrationOK handles this case with default header values.

Redirect info fetch success
*/
type RedirectIntegrationOK struct {
	Payload *models.IntegrationRedirect
}

func (o *RedirectIntegrationOK) Error() string {
	return fmt.Sprintf("[GET /api/integrations/{providerId}/redirect][%d] redirectIntegrationOK  %+v", 200, o.Payload)
}

func (o *RedirectIntegrationOK) GetPayload() *models.IntegrationRedirect {
	return o.Payload
}

func (o *RedirectIntegrationOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.IntegrationRedirect)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
