// Code generated by go-swagger; DO NOT EDIT.

package workflows_v1

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewDeleteWorkflowParams creates a new DeleteWorkflowParams object
// with the default values initialized.
func NewDeleteWorkflowParams() *DeleteWorkflowParams {
	var ()
	return &DeleteWorkflowParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewDeleteWorkflowParamsWithTimeout creates a new DeleteWorkflowParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewDeleteWorkflowParamsWithTimeout(timeout time.Duration) *DeleteWorkflowParams {
	var ()
	return &DeleteWorkflowParams{

		timeout: timeout,
	}
}

// NewDeleteWorkflowParamsWithContext creates a new DeleteWorkflowParams object
// with the default values initialized, and the ability to set a context for a request
func NewDeleteWorkflowParamsWithContext(ctx context.Context) *DeleteWorkflowParams {
	var ()
	return &DeleteWorkflowParams{

		Context: ctx,
	}
}

// NewDeleteWorkflowParamsWithHTTPClient creates a new DeleteWorkflowParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewDeleteWorkflowParamsWithHTTPClient(client *http.Client) *DeleteWorkflowParams {
	var ()
	return &DeleteWorkflowParams{
		HTTPClient: client,
	}
}

/*DeleteWorkflowParams contains all the parameters to send to the API endpoint
for the delete workflow operation typically these are written to a http.Request
*/
type DeleteWorkflowParams struct {

	/*Accept
	  The version of the API, in this case should be "application/nebula-api.v1+json"

	*/
	Accept string
	/*ID
	  ID of the workflow to delete

	*/
	ID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the delete workflow params
func (o *DeleteWorkflowParams) WithTimeout(timeout time.Duration) *DeleteWorkflowParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the delete workflow params
func (o *DeleteWorkflowParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the delete workflow params
func (o *DeleteWorkflowParams) WithContext(ctx context.Context) *DeleteWorkflowParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the delete workflow params
func (o *DeleteWorkflowParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the delete workflow params
func (o *DeleteWorkflowParams) WithHTTPClient(client *http.Client) *DeleteWorkflowParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the delete workflow params
func (o *DeleteWorkflowParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithAccept adds the accept to the delete workflow params
func (o *DeleteWorkflowParams) WithAccept(accept string) *DeleteWorkflowParams {
	o.SetAccept(accept)
	return o
}

// SetAccept adds the accept to the delete workflow params
func (o *DeleteWorkflowParams) SetAccept(accept string) {
	o.Accept = accept
}

// WithID adds the id to the delete workflow params
func (o *DeleteWorkflowParams) WithID(id string) *DeleteWorkflowParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the delete workflow params
func (o *DeleteWorkflowParams) SetID(id string) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *DeleteWorkflowParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// header param Accept
	if err := r.SetHeaderParam("Accept", o.Accept); err != nil {
		return err
	}

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
