// Code generated by go-swagger; DO NOT EDIT.

package workflow_triggers

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewCreateWorkflowTriggerParams creates a new CreateWorkflowTriggerParams object
// with the default values initialized.
func NewCreateWorkflowTriggerParams() *CreateWorkflowTriggerParams {
	var ()
	return &CreateWorkflowTriggerParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewCreateWorkflowTriggerParamsWithTimeout creates a new CreateWorkflowTriggerParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewCreateWorkflowTriggerParamsWithTimeout(timeout time.Duration) *CreateWorkflowTriggerParams {
	var ()
	return &CreateWorkflowTriggerParams{

		timeout: timeout,
	}
}

// NewCreateWorkflowTriggerParamsWithContext creates a new CreateWorkflowTriggerParams object
// with the default values initialized, and the ability to set a context for a request
func NewCreateWorkflowTriggerParamsWithContext(ctx context.Context) *CreateWorkflowTriggerParams {
	var ()
	return &CreateWorkflowTriggerParams{

		Context: ctx,
	}
}

// NewCreateWorkflowTriggerParamsWithHTTPClient creates a new CreateWorkflowTriggerParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewCreateWorkflowTriggerParamsWithHTTPClient(client *http.Client) *CreateWorkflowTriggerParams {
	var ()
	return &CreateWorkflowTriggerParams{
		HTTPClient: client,
	}
}

/*CreateWorkflowTriggerParams contains all the parameters to send to the API endpoint
for the create workflow trigger operation typically these are written to a http.Request
*/
type CreateWorkflowTriggerParams struct {

	/*Body
	  The workflow trigger to create

	*/
	Body CreateWorkflowTriggerBody
	/*WorkflowName
	  Workflow name

	*/
	WorkflowName string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the create workflow trigger params
func (o *CreateWorkflowTriggerParams) WithTimeout(timeout time.Duration) *CreateWorkflowTriggerParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the create workflow trigger params
func (o *CreateWorkflowTriggerParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the create workflow trigger params
func (o *CreateWorkflowTriggerParams) WithContext(ctx context.Context) *CreateWorkflowTriggerParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the create workflow trigger params
func (o *CreateWorkflowTriggerParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the create workflow trigger params
func (o *CreateWorkflowTriggerParams) WithHTTPClient(client *http.Client) *CreateWorkflowTriggerParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the create workflow trigger params
func (o *CreateWorkflowTriggerParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the create workflow trigger params
func (o *CreateWorkflowTriggerParams) WithBody(body CreateWorkflowTriggerBody) *CreateWorkflowTriggerParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the create workflow trigger params
func (o *CreateWorkflowTriggerParams) SetBody(body CreateWorkflowTriggerBody) {
	o.Body = body
}

// WithWorkflowName adds the workflowName to the create workflow trigger params
func (o *CreateWorkflowTriggerParams) WithWorkflowName(workflowName string) *CreateWorkflowTriggerParams {
	o.SetWorkflowName(workflowName)
	return o
}

// SetWorkflowName adds the workflowName to the create workflow trigger params
func (o *CreateWorkflowTriggerParams) SetWorkflowName(workflowName string) {
	o.WorkflowName = workflowName
}

// WriteToRequest writes these params to a swagger request
func (o *CreateWorkflowTriggerParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if err := r.SetBodyParam(o.Body); err != nil {
		return err
	}

	// path param workflowName
	if err := r.SetPathParam("workflowName", o.WorkflowName); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
