// Code generated by go-swagger; DO NOT EDIT.

package workflow_triggers

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/puppetlabs/nebula-cli/pkg/client/api/models"
)

// GetWorkflowTriggerReader is a Reader for the GetWorkflowTrigger structure.
type GetWorkflowTriggerReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetWorkflowTriggerReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetWorkflowTriggerOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewGetWorkflowTriggerDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewGetWorkflowTriggerOK creates a GetWorkflowTriggerOK with default headers values
func NewGetWorkflowTriggerOK() *GetWorkflowTriggerOK {
	return &GetWorkflowTriggerOK{}
}

/*GetWorkflowTriggerOK handles this case with default header values.

A workflow trigger
*/
type GetWorkflowTriggerOK struct {
	Payload *GetWorkflowTriggerOKBody
}

func (o *GetWorkflowTriggerOK) Error() string {
	return fmt.Sprintf("[GET /api/workflows/{workflowName}/triggers/{workflowTriggerId}][%d] getWorkflowTriggerOK  %+v", 200, o.Payload)
}

func (o *GetWorkflowTriggerOK) GetPayload() *GetWorkflowTriggerOKBody {
	return o.Payload
}

func (o *GetWorkflowTriggerOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(GetWorkflowTriggerOKBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetWorkflowTriggerDefault creates a GetWorkflowTriggerDefault with default headers values
func NewGetWorkflowTriggerDefault(code int) *GetWorkflowTriggerDefault {
	return &GetWorkflowTriggerDefault{
		_statusCode: code,
	}
}

/*GetWorkflowTriggerDefault handles this case with default header values.

An error occurred
*/
type GetWorkflowTriggerDefault struct {
	_statusCode int

	Payload *GetWorkflowTriggerDefaultBody
}

// Code gets the status code for the get workflow trigger default response
func (o *GetWorkflowTriggerDefault) Code() int {
	return o._statusCode
}

func (o *GetWorkflowTriggerDefault) Error() string {
	return fmt.Sprintf("[GET /api/workflows/{workflowName}/triggers/{workflowTriggerId}][%d] getWorkflowTrigger default  %+v", o._statusCode, o.Payload)
}

func (o *GetWorkflowTriggerDefault) GetPayload() *GetWorkflowTriggerDefaultBody {
	return o.Payload
}

func (o *GetWorkflowTriggerDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(GetWorkflowTriggerDefaultBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

/*GetWorkflowTriggerDefaultBody Error response
swagger:model GetWorkflowTriggerDefaultBody
*/
type GetWorkflowTriggerDefaultBody struct {

	// error
	Error *models.Error `json:"error,omitempty"`
}

// Validate validates this get workflow trigger default body
func (o *GetWorkflowTriggerDefaultBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateError(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *GetWorkflowTriggerDefaultBody) validateError(formats strfmt.Registry) error {

	if swag.IsZero(o.Error) { // not required
		return nil
	}

	if o.Error != nil {
		if err := o.Error.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("getWorkflowTrigger default" + "." + "error")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (o *GetWorkflowTriggerDefaultBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *GetWorkflowTriggerDefaultBody) UnmarshalBinary(b []byte) error {
	var res GetWorkflowTriggerDefaultBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}

/*GetWorkflowTriggerOKBody The response type for a trigger
swagger:model GetWorkflowTriggerOKBody
*/
type GetWorkflowTriggerOKBody struct {

	// trigger
	Trigger *models.WorkflowTrigger `json:"trigger,omitempty"`
}

// Validate validates this get workflow trigger o k body
func (o *GetWorkflowTriggerOKBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateTrigger(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *GetWorkflowTriggerOKBody) validateTrigger(formats strfmt.Registry) error {

	if swag.IsZero(o.Trigger) { // not required
		return nil
	}

	if o.Trigger != nil {
		if err := o.Trigger.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("getWorkflowTriggerOK" + "." + "trigger")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (o *GetWorkflowTriggerOKBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *GetWorkflowTriggerOKBody) UnmarshalBinary(b []byte) error {
	var res GetWorkflowTriggerOKBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
