// Code generated by go-swagger; DO NOT EDIT.

package workflow_triggers

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetWorkflowTriggerParams creates a new GetWorkflowTriggerParams object
// with the default values initialized.
func NewGetWorkflowTriggerParams() *GetWorkflowTriggerParams {
	var ()
	return &GetWorkflowTriggerParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetWorkflowTriggerParamsWithTimeout creates a new GetWorkflowTriggerParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetWorkflowTriggerParamsWithTimeout(timeout time.Duration) *GetWorkflowTriggerParams {
	var ()
	return &GetWorkflowTriggerParams{

		timeout: timeout,
	}
}

// NewGetWorkflowTriggerParamsWithContext creates a new GetWorkflowTriggerParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetWorkflowTriggerParamsWithContext(ctx context.Context) *GetWorkflowTriggerParams {
	var ()
	return &GetWorkflowTriggerParams{

		Context: ctx,
	}
}

// NewGetWorkflowTriggerParamsWithHTTPClient creates a new GetWorkflowTriggerParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetWorkflowTriggerParamsWithHTTPClient(client *http.Client) *GetWorkflowTriggerParams {
	var ()
	return &GetWorkflowTriggerParams{
		HTTPClient: client,
	}
}

/*GetWorkflowTriggerParams contains all the parameters to send to the API endpoint
for the get workflow trigger operation typically these are written to a http.Request
*/
type GetWorkflowTriggerParams struct {

	/*WorkflowName
	  Workflow name

	*/
	WorkflowName string
	/*WorkflowTriggerID
	  The workflow trigger ID to reference

	*/
	WorkflowTriggerID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get workflow trigger params
func (o *GetWorkflowTriggerParams) WithTimeout(timeout time.Duration) *GetWorkflowTriggerParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get workflow trigger params
func (o *GetWorkflowTriggerParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get workflow trigger params
func (o *GetWorkflowTriggerParams) WithContext(ctx context.Context) *GetWorkflowTriggerParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get workflow trigger params
func (o *GetWorkflowTriggerParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get workflow trigger params
func (o *GetWorkflowTriggerParams) WithHTTPClient(client *http.Client) *GetWorkflowTriggerParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get workflow trigger params
func (o *GetWorkflowTriggerParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithWorkflowName adds the workflowName to the get workflow trigger params
func (o *GetWorkflowTriggerParams) WithWorkflowName(workflowName string) *GetWorkflowTriggerParams {
	o.SetWorkflowName(workflowName)
	return o
}

// SetWorkflowName adds the workflowName to the get workflow trigger params
func (o *GetWorkflowTriggerParams) SetWorkflowName(workflowName string) {
	o.WorkflowName = workflowName
}

// WithWorkflowTriggerID adds the workflowTriggerID to the get workflow trigger params
func (o *GetWorkflowTriggerParams) WithWorkflowTriggerID(workflowTriggerID string) *GetWorkflowTriggerParams {
	o.SetWorkflowTriggerID(workflowTriggerID)
	return o
}

// SetWorkflowTriggerID adds the workflowTriggerId to the get workflow trigger params
func (o *GetWorkflowTriggerParams) SetWorkflowTriggerID(workflowTriggerID string) {
	o.WorkflowTriggerID = workflowTriggerID
}

// WriteToRequest writes these params to a swagger request
func (o *GetWorkflowTriggerParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param workflowName
	if err := r.SetPathParam("workflowName", o.WorkflowName); err != nil {
		return err
	}

	// path param workflowTriggerId
	if err := r.SetPathParam("workflowTriggerId", o.WorkflowTriggerID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
