// Code generated by go-swagger; DO NOT EDIT.

package workflow_triggers

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewUpdateWorkflowTriggerParams creates a new UpdateWorkflowTriggerParams object
// with the default values initialized.
func NewUpdateWorkflowTriggerParams() *UpdateWorkflowTriggerParams {
	var ()
	return &UpdateWorkflowTriggerParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewUpdateWorkflowTriggerParamsWithTimeout creates a new UpdateWorkflowTriggerParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewUpdateWorkflowTriggerParamsWithTimeout(timeout time.Duration) *UpdateWorkflowTriggerParams {
	var ()
	return &UpdateWorkflowTriggerParams{

		timeout: timeout,
	}
}

// NewUpdateWorkflowTriggerParamsWithContext creates a new UpdateWorkflowTriggerParams object
// with the default values initialized, and the ability to set a context for a request
func NewUpdateWorkflowTriggerParamsWithContext(ctx context.Context) *UpdateWorkflowTriggerParams {
	var ()
	return &UpdateWorkflowTriggerParams{

		Context: ctx,
	}
}

// NewUpdateWorkflowTriggerParamsWithHTTPClient creates a new UpdateWorkflowTriggerParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewUpdateWorkflowTriggerParamsWithHTTPClient(client *http.Client) *UpdateWorkflowTriggerParams {
	var ()
	return &UpdateWorkflowTriggerParams{
		HTTPClient: client,
	}
}

/*UpdateWorkflowTriggerParams contains all the parameters to send to the API endpoint
for the update workflow trigger operation typically these are written to a http.Request
*/
type UpdateWorkflowTriggerParams struct {

	/*Body
	  The updated settings and binding for a workflow trigger

	*/
	Body UpdateWorkflowTriggerBody
	/*WorkflowName
	  Workflow name

	*/
	WorkflowName string
	/*WorkflowTriggerID
	  The workflow trigger ID to reference

	*/
	WorkflowTriggerID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the update workflow trigger params
func (o *UpdateWorkflowTriggerParams) WithTimeout(timeout time.Duration) *UpdateWorkflowTriggerParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the update workflow trigger params
func (o *UpdateWorkflowTriggerParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the update workflow trigger params
func (o *UpdateWorkflowTriggerParams) WithContext(ctx context.Context) *UpdateWorkflowTriggerParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the update workflow trigger params
func (o *UpdateWorkflowTriggerParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the update workflow trigger params
func (o *UpdateWorkflowTriggerParams) WithHTTPClient(client *http.Client) *UpdateWorkflowTriggerParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the update workflow trigger params
func (o *UpdateWorkflowTriggerParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the update workflow trigger params
func (o *UpdateWorkflowTriggerParams) WithBody(body UpdateWorkflowTriggerBody) *UpdateWorkflowTriggerParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the update workflow trigger params
func (o *UpdateWorkflowTriggerParams) SetBody(body UpdateWorkflowTriggerBody) {
	o.Body = body
}

// WithWorkflowName adds the workflowName to the update workflow trigger params
func (o *UpdateWorkflowTriggerParams) WithWorkflowName(workflowName string) *UpdateWorkflowTriggerParams {
	o.SetWorkflowName(workflowName)
	return o
}

// SetWorkflowName adds the workflowName to the update workflow trigger params
func (o *UpdateWorkflowTriggerParams) SetWorkflowName(workflowName string) {
	o.WorkflowName = workflowName
}

// WithWorkflowTriggerID adds the workflowTriggerID to the update workflow trigger params
func (o *UpdateWorkflowTriggerParams) WithWorkflowTriggerID(workflowTriggerID string) *UpdateWorkflowTriggerParams {
	o.SetWorkflowTriggerID(workflowTriggerID)
	return o
}

// SetWorkflowTriggerID adds the workflowTriggerId to the update workflow trigger params
func (o *UpdateWorkflowTriggerParams) SetWorkflowTriggerID(workflowTriggerID string) {
	o.WorkflowTriggerID = workflowTriggerID
}

// WriteToRequest writes these params to a swagger request
func (o *UpdateWorkflowTriggerParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if err := r.SetBodyParam(o.Body); err != nil {
		return err
	}

	// path param workflowName
	if err := r.SetPathParam("workflowName", o.WorkflowName); err != nil {
		return err
	}

	// path param workflowTriggerId
	if err := r.SetPathParam("workflowTriggerId", o.WorkflowTriggerID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
