// Code generated by go-swagger; DO NOT EDIT.

package workflow_runs_v1

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetWorkflowRunLogsParams creates a new GetWorkflowRunLogsParams object
// with the default values initialized.
func NewGetWorkflowRunLogsParams() *GetWorkflowRunLogsParams {
	var ()
	return &GetWorkflowRunLogsParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetWorkflowRunLogsParamsWithTimeout creates a new GetWorkflowRunLogsParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetWorkflowRunLogsParamsWithTimeout(timeout time.Duration) *GetWorkflowRunLogsParams {
	var ()
	return &GetWorkflowRunLogsParams{

		timeout: timeout,
	}
}

// NewGetWorkflowRunLogsParamsWithContext creates a new GetWorkflowRunLogsParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetWorkflowRunLogsParamsWithContext(ctx context.Context) *GetWorkflowRunLogsParams {
	var ()
	return &GetWorkflowRunLogsParams{

		Context: ctx,
	}
}

// NewGetWorkflowRunLogsParamsWithHTTPClient creates a new GetWorkflowRunLogsParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetWorkflowRunLogsParamsWithHTTPClient(client *http.Client) *GetWorkflowRunLogsParams {
	var ()
	return &GetWorkflowRunLogsParams{
		HTTPClient: client,
	}
}

/*GetWorkflowRunLogsParams contains all the parameters to send to the API endpoint
for the get workflow run logs operation typically these are written to a http.Request
*/
type GetWorkflowRunLogsParams struct {

	/*Accept
	  The version of the API, in this case should be "application/nebula-api.v1+json"

	*/
	Accept string
	/*RunNumber
	  Inrecrmented run number of the associated workflow

	*/
	RunNumber int64
	/*WorkflowName
	  Workflow name. Must be unique within a user account

	*/
	WorkflowName string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get workflow run logs params
func (o *GetWorkflowRunLogsParams) WithTimeout(timeout time.Duration) *GetWorkflowRunLogsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get workflow run logs params
func (o *GetWorkflowRunLogsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get workflow run logs params
func (o *GetWorkflowRunLogsParams) WithContext(ctx context.Context) *GetWorkflowRunLogsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get workflow run logs params
func (o *GetWorkflowRunLogsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get workflow run logs params
func (o *GetWorkflowRunLogsParams) WithHTTPClient(client *http.Client) *GetWorkflowRunLogsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get workflow run logs params
func (o *GetWorkflowRunLogsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithAccept adds the accept to the get workflow run logs params
func (o *GetWorkflowRunLogsParams) WithAccept(accept string) *GetWorkflowRunLogsParams {
	o.SetAccept(accept)
	return o
}

// SetAccept adds the accept to the get workflow run logs params
func (o *GetWorkflowRunLogsParams) SetAccept(accept string) {
	o.Accept = accept
}

// WithRunNumber adds the runNumber to the get workflow run logs params
func (o *GetWorkflowRunLogsParams) WithRunNumber(runNumber int64) *GetWorkflowRunLogsParams {
	o.SetRunNumber(runNumber)
	return o
}

// SetRunNumber adds the runNumber to the get workflow run logs params
func (o *GetWorkflowRunLogsParams) SetRunNumber(runNumber int64) {
	o.RunNumber = runNumber
}

// WithWorkflowName adds the workflowName to the get workflow run logs params
func (o *GetWorkflowRunLogsParams) WithWorkflowName(workflowName string) *GetWorkflowRunLogsParams {
	o.SetWorkflowName(workflowName)
	return o
}

// SetWorkflowName adds the workflowName to the get workflow run logs params
func (o *GetWorkflowRunLogsParams) SetWorkflowName(workflowName string) {
	o.WorkflowName = workflowName
}

// WriteToRequest writes these params to a swagger request
func (o *GetWorkflowRunLogsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// header param Accept
	if err := r.SetHeaderParam("Accept", o.Accept); err != nil {
		return err
	}

	// path param run_number
	if err := r.SetPathParam("run_number", swag.FormatInt64(o.RunNumber)); err != nil {
		return err
	}

	// path param workflow_name
	if err := r.SetPathParam("workflow_name", o.WorkflowName); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
