// Code generated by go-swagger; DO NOT EDIT.

package workflow_secrets_v1

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/puppetlabs/nebula/pkg/client/api/models"
)

// CreateWorkflowSecretReader is a Reader for the CreateWorkflowSecret structure.
type CreateWorkflowSecretReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *CreateWorkflowSecretReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 201:
		result := NewCreateWorkflowSecretCreated()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 409:
		result := NewCreateWorkflowSecretConflict()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewCreateWorkflowSecretCreated creates a CreateWorkflowSecretCreated with default headers values
func NewCreateWorkflowSecretCreated() *CreateWorkflowSecretCreated {
	return &CreateWorkflowSecretCreated{}
}

/*CreateWorkflowSecretCreated handles this case with default header values.

Summary of newly created secret
*/
type CreateWorkflowSecretCreated struct {
	Payload *models.SecretSummary
}

func (o *CreateWorkflowSecretCreated) Error() string {
	return fmt.Sprintf("[POST /api/workflows/{workflow_name}/secrets][%d] createWorkflowSecretCreated  %+v", 201, o.Payload)
}

func (o *CreateWorkflowSecretCreated) GetPayload() *models.SecretSummary {
	return o.Payload
}

func (o *CreateWorkflowSecretCreated) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.SecretSummary)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewCreateWorkflowSecretConflict creates a CreateWorkflowSecretConflict with default headers values
func NewCreateWorkflowSecretConflict() *CreateWorkflowSecretConflict {
	return &CreateWorkflowSecretConflict{}
}

/*CreateWorkflowSecretConflict handles this case with default header values.

A secret belonging to that workflow already exists with that name
*/
type CreateWorkflowSecretConflict struct {
	Payload *models.ErrawrResponse
}

func (o *CreateWorkflowSecretConflict) Error() string {
	return fmt.Sprintf("[POST /api/workflows/{workflow_name}/secrets][%d] createWorkflowSecretConflict  %+v", 409, o.Payload)
}

func (o *CreateWorkflowSecretConflict) GetPayload() *models.ErrawrResponse {
	return o.Payload
}

func (o *CreateWorkflowSecretConflict) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrawrResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
