// Code generated by go-swagger; DO NOT EDIT.

package workflow_secrets_v1

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetReferencedSecretsParams creates a new GetReferencedSecretsParams object
// with the default values initialized.
func NewGetReferencedSecretsParams() *GetReferencedSecretsParams {
	var ()
	return &GetReferencedSecretsParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetReferencedSecretsParamsWithTimeout creates a new GetReferencedSecretsParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetReferencedSecretsParamsWithTimeout(timeout time.Duration) *GetReferencedSecretsParams {
	var ()
	return &GetReferencedSecretsParams{

		timeout: timeout,
	}
}

// NewGetReferencedSecretsParamsWithContext creates a new GetReferencedSecretsParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetReferencedSecretsParamsWithContext(ctx context.Context) *GetReferencedSecretsParams {
	var ()
	return &GetReferencedSecretsParams{

		Context: ctx,
	}
}

// NewGetReferencedSecretsParamsWithHTTPClient creates a new GetReferencedSecretsParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetReferencedSecretsParamsWithHTTPClient(client *http.Client) *GetReferencedSecretsParams {
	var ()
	return &GetReferencedSecretsParams{
		HTTPClient: client,
	}
}

/*GetReferencedSecretsParams contains all the parameters to send to the API endpoint
for the get referenced secrets operation typically these are written to a http.Request
*/
type GetReferencedSecretsParams struct {

	/*Accept
	  The version of the API, in this case should be "application/nebula-api.v1+json"

	*/
	Accept string
	/*Key
	  The key of the secret we want to update (unique to the workflow)

	*/
	Key string
	/*RunNumber
	  The run number for which we wish to see the secrets it references

	*/
	RunNumber string
	/*WorkflowName
	  Workflow name. Must be unique within a user account

	*/
	WorkflowName string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get referenced secrets params
func (o *GetReferencedSecretsParams) WithTimeout(timeout time.Duration) *GetReferencedSecretsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get referenced secrets params
func (o *GetReferencedSecretsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get referenced secrets params
func (o *GetReferencedSecretsParams) WithContext(ctx context.Context) *GetReferencedSecretsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get referenced secrets params
func (o *GetReferencedSecretsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get referenced secrets params
func (o *GetReferencedSecretsParams) WithHTTPClient(client *http.Client) *GetReferencedSecretsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get referenced secrets params
func (o *GetReferencedSecretsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithAccept adds the accept to the get referenced secrets params
func (o *GetReferencedSecretsParams) WithAccept(accept string) *GetReferencedSecretsParams {
	o.SetAccept(accept)
	return o
}

// SetAccept adds the accept to the get referenced secrets params
func (o *GetReferencedSecretsParams) SetAccept(accept string) {
	o.Accept = accept
}

// WithKey adds the key to the get referenced secrets params
func (o *GetReferencedSecretsParams) WithKey(key string) *GetReferencedSecretsParams {
	o.SetKey(key)
	return o
}

// SetKey adds the key to the get referenced secrets params
func (o *GetReferencedSecretsParams) SetKey(key string) {
	o.Key = key
}

// WithRunNumber adds the runNumber to the get referenced secrets params
func (o *GetReferencedSecretsParams) WithRunNumber(runNumber string) *GetReferencedSecretsParams {
	o.SetRunNumber(runNumber)
	return o
}

// SetRunNumber adds the runNumber to the get referenced secrets params
func (o *GetReferencedSecretsParams) SetRunNumber(runNumber string) {
	o.RunNumber = runNumber
}

// WithWorkflowName adds the workflowName to the get referenced secrets params
func (o *GetReferencedSecretsParams) WithWorkflowName(workflowName string) *GetReferencedSecretsParams {
	o.SetWorkflowName(workflowName)
	return o
}

// SetWorkflowName adds the workflowName to the get referenced secrets params
func (o *GetReferencedSecretsParams) SetWorkflowName(workflowName string) {
	o.WorkflowName = workflowName
}

// WriteToRequest writes these params to a swagger request
func (o *GetReferencedSecretsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// header param Accept
	if err := r.SetHeaderParam("Accept", o.Accept); err != nil {
		return err
	}

	// path param key
	if err := r.SetPathParam("key", o.Key); err != nil {
		return err
	}

	// path param run_number
	if err := r.SetPathParam("run_number", o.RunNumber); err != nil {
		return err
	}

	// path param workflow_name
	if err := r.SetPathParam("workflow_name", o.WorkflowName); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
