// Code generated by go-swagger; DO NOT EDIT.

package notifications

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewPostNotificationReadParams creates a new PostNotificationReadParams object
// with the default values initialized.
func NewPostNotificationReadParams() *PostNotificationReadParams {
	var ()
	return &PostNotificationReadParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewPostNotificationReadParamsWithTimeout creates a new PostNotificationReadParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewPostNotificationReadParamsWithTimeout(timeout time.Duration) *PostNotificationReadParams {
	var ()
	return &PostNotificationReadParams{

		timeout: timeout,
	}
}

// NewPostNotificationReadParamsWithContext creates a new PostNotificationReadParams object
// with the default values initialized, and the ability to set a context for a request
func NewPostNotificationReadParamsWithContext(ctx context.Context) *PostNotificationReadParams {
	var ()
	return &PostNotificationReadParams{

		Context: ctx,
	}
}

// NewPostNotificationReadParamsWithHTTPClient creates a new PostNotificationReadParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewPostNotificationReadParamsWithHTTPClient(client *http.Client) *PostNotificationReadParams {
	var ()
	return &PostNotificationReadParams{
		HTTPClient: client,
	}
}

/*PostNotificationReadParams contains all the parameters to send to the API endpoint
for the post notification read operation typically these are written to a http.Request
*/
type PostNotificationReadParams struct {

	/*NotificationID
	  The notification ID

	*/
	NotificationID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the post notification read params
func (o *PostNotificationReadParams) WithTimeout(timeout time.Duration) *PostNotificationReadParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the post notification read params
func (o *PostNotificationReadParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the post notification read params
func (o *PostNotificationReadParams) WithContext(ctx context.Context) *PostNotificationReadParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the post notification read params
func (o *PostNotificationReadParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the post notification read params
func (o *PostNotificationReadParams) WithHTTPClient(client *http.Client) *PostNotificationReadParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the post notification read params
func (o *PostNotificationReadParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithNotificationID adds the notificationID to the post notification read params
func (o *PostNotificationReadParams) WithNotificationID(notificationID string) *PostNotificationReadParams {
	o.SetNotificationID(notificationID)
	return o
}

// SetNotificationID adds the notificationId to the post notification read params
func (o *PostNotificationReadParams) SetNotificationID(notificationID string) {
	o.NotificationID = notificationID
}

// WriteToRequest writes these params to a swagger request
func (o *PostNotificationReadParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param notificationId
	if err := r.SetPathParam("notificationId", o.NotificationID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
