// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// EventSourceProviderSystem An event source provided by the system
//
// swagger:model EventSourceProviderSystem
type EventSourceProviderSystem struct {

	// type
	// Required: true
	// Enum: [system]
	Type *string `json:"type"`
}

// Validate validates this event source provider system
func (m *EventSourceProviderSystem) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateType(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

var eventSourceProviderSystemTypeTypePropEnum []interface{}

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["system"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		eventSourceProviderSystemTypeTypePropEnum = append(eventSourceProviderSystemTypeTypePropEnum, v)
	}
}

const (

	// EventSourceProviderSystemTypeSystem captures enum value "system"
	EventSourceProviderSystemTypeSystem string = "system"
)

// prop value enum
func (m *EventSourceProviderSystem) validateTypeEnum(path, location string, value string) error {
	if err := validate.Enum(path, location, value, eventSourceProviderSystemTypeTypePropEnum); err != nil {
		return err
	}
	return nil
}

func (m *EventSourceProviderSystem) validateType(formats strfmt.Registry) error {

	if err := validate.Required("type", "body", m.Type); err != nil {
		return err
	}

	// value enum
	if err := m.validateTypeEnum("type", "body", *m.Type); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *EventSourceProviderSystem) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *EventSourceProviderSystem) UnmarshalBinary(b []byte) error {
	var res EventSourceProviderSystem
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
