// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// IntegrationRevision integration revision
// swagger:model IntegrationRevision
type IntegrationRevision struct {
	Lifecycle

	// This integration's provider identifier
	// Required: true
	Provider *string `json:"provider"`
}

// UnmarshalJSON unmarshals this object from a JSON structure
func (m *IntegrationRevision) UnmarshalJSON(raw []byte) error {
	// AO0
	var aO0 Lifecycle
	if err := swag.ReadJSON(raw, &aO0); err != nil {
		return err
	}
	m.Lifecycle = aO0

	// AO1
	var dataAO1 struct {
		Provider *string `json:"provider"`
	}
	if err := swag.ReadJSON(raw, &dataAO1); err != nil {
		return err
	}

	m.Provider = dataAO1.Provider

	return nil
}

// MarshalJSON marshals this object to a JSON structure
func (m IntegrationRevision) MarshalJSON() ([]byte, error) {
	_parts := make([][]byte, 0, 2)

	aO0, err := swag.WriteJSON(m.Lifecycle)
	if err != nil {
		return nil, err
	}
	_parts = append(_parts, aO0)

	var dataAO1 struct {
		Provider *string `json:"provider"`
	}

	dataAO1.Provider = m.Provider

	jsonDataAO1, errAO1 := swag.WriteJSON(dataAO1)
	if errAO1 != nil {
		return nil, errAO1
	}
	_parts = append(_parts, jsonDataAO1)

	return swag.ConcatJSON(_parts...), nil
}

// Validate validates this integration revision
func (m *IntegrationRevision) Validate(formats strfmt.Registry) error {
	var res []error

	// validation for a type composition with Lifecycle
	if err := m.Lifecycle.Validate(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateProvider(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *IntegrationRevision) validateProvider(formats strfmt.Registry) error {

	if err := validate.Required("provider", "body", m.Provider); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *IntegrationRevision) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *IntegrationRevision) UnmarshalBinary(b []byte) error {
	var res IntegrationRevision
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
