// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/swag"
)

// UpdateIntegrationSubmission The editable fields of a nebula external integration entry
// swagger:model UpdateIntegrationSubmission
type UpdateIntegrationSubmission struct {

	// A descriptive integration name
	Name string `json:"name,omitempty"`
}

// Validate validates this update integration submission
func (m *UpdateIntegrationSubmission) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *UpdateIntegrationSubmission) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *UpdateIntegrationSubmission) UnmarshalBinary(b []byte) error {
	var res UpdateIntegrationSubmission
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
