// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// WorkflowRunParameter workflow run parameter
//
// swagger:model WorkflowRunParameter
type WorkflowRunParameter struct {

	// A defined value for the parameter
	Value interface{} `json:"value,omitempty"`
}

// Validate validates this workflow run parameter
func (m *WorkflowRunParameter) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *WorkflowRunParameter) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *WorkflowRunParameter) UnmarshalBinary(b []byte) error {
	var res WorkflowRunParameter
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
