// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package main

import (
	"context"
	"github.com/puppetlabs/relay/pkg/vault/op/vault"
	"github.com/puppetlabs/relay/pkg/vault/opt"
)

// Injectors from wire.go:

func InitializeServices(ctx context.Context, cfg *opt.Config) (services, error) {
	config := vaultConfig(cfg)
	client, err := vault.NewClient(ctx, config)
	if err != nil {
		return services{}, err
	}
	mainServices := services{
		vault: client,
	}
	return mainServices, nil
}

// wire.go:

func vaultConfig(cfg *opt.Config) vault.Config {
	return vault.Config{
		Addr: cfg.VaultAddr.String(),
	}
}
