#!/usr/bin/env bash
set -euo pipefail

#
# Commands
#

MKDIR_P="${MKDIR_P:-mkdir -p}"
GO="${GO:-go}"
TAR="${TAR:-tar}"
ZIP_M="${ZIP_M:-zip -m}"

#
# Variables
#

GOOS="$( $GO env GOOS )"
GOARCH="$( $GO env GOARCH )"

#
#
#

. scripts/library.sh

relay::cli::release_check
eval "$( relay::cli::cli_vars )"

ARTIFACTS_CLI_DIR="bin"

BIN_DIR="${ARTIFACTS_CLI_DIR}" \
  CGO_ENABLED=0 \
  GOFLAGS="${GOFLAGS:-} -a" \
  LDFLAGS="${LDFLAGS:-}"' -extldflags "-static"' \
  scripts/build "${CLI_NAME}"

case "$( $GO env GOOS )" in
windows)
  (
    set -x
    pushd "${ARTIFACTS_CLI_DIR}" >/dev/null
    relay::cli::sha256sum <"${CLI_FILE_PREFIX}.exe" >"${CLI_FILE_PREFIX}.exe.sha256"
  )
  ;;
*)
  (
    set -x
    pushd "${ARTIFACTS_CLI_DIR}" >/dev/null
    relay::cli::sha256sum <"${CLI_FILE_PREFIX}" >"${CLI_FILE_PREFIX}.sha256"
  )
  ;;
esac

set +x
