#!/usr/bin/env bash
set -euo pipefail

. scripts/library.sh

GO_DIST_OS_ARCHES=( linux-amd64 windows-amd64 darwin-amd64 )

for OS_ARCH in "${GO_DIST_OS_ARCHES[@]}"; do
  echo "# dist (go): relay ${OS_ARCH}"
  GOOS="${OS_ARCH%-*}" GOARCH="${OS_ARCH##*-}" scripts/dist
done
