#!/bin/bash
set -euo pipefail

TAG=${TRAVIS_TAG}
CLI="bin/relay-${TAG}-linux-amd64"
SHA=$(<"bin/relay-${TAG}-darwin-amd64.sha256")

chmod +x $CLI

echo -n "${RELAY_OPERATIONS_API_TOKEN}" | ${CLI} auth login --stdin

${CLI} workflow run --parameter tag=${TAG} --parameter sha=${SHA} relay-cli-update-brew
