#!/bin/bash

TAG=${TRAVIS_TAG}
CLI="bin/relay-${TAG}-linux-amd64"
SHA=$(<"bin/relay-${TAG}-darwin-amd64.sha256")

chmod +x $CLI

echo -n "${RELAY_PASSWORD}" | ${CLI} auth login "${RELAY_EMAIL}" -p\

${CLI} workflow run --parameter tag=${TAG} --parameter sha=${SHA} relay-cli-update-brew
