/*
 * Relay API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: v20200615
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// PermissionIdentifier A unique identifier for a system permission
type PermissionIdentifier struct {
	// The name of the permission
	Name string `json:"name"`
}

// NewPermissionIdentifier instantiates a new PermissionIdentifier object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPermissionIdentifier(name string) *PermissionIdentifier {
	this := PermissionIdentifier{}
	this.Name = name
	return &this
}

// NewPermissionIdentifierWithDefaults instantiates a new PermissionIdentifier object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPermissionIdentifierWithDefaults() *PermissionIdentifier {
	this := PermissionIdentifier{}
	return &this
}

// GetName returns the Name field value
func (o *PermissionIdentifier) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *PermissionIdentifier) GetNameOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *PermissionIdentifier) SetName(v string) {
	o.Name = v
}

func (o PermissionIdentifier) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["name"] = o.Name
	}
	return json.Marshal(toSerialize)
}

type NullablePermissionIdentifier struct {
	value *PermissionIdentifier
	isSet bool
}

func (v NullablePermissionIdentifier) Get() *PermissionIdentifier {
	return v.value
}

func (v *NullablePermissionIdentifier) Set(val *PermissionIdentifier) {
	v.value = val
	v.isSet = true
}

func (v NullablePermissionIdentifier) IsSet() bool {
	return v.isSet
}

func (v *NullablePermissionIdentifier) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePermissionIdentifier(val *PermissionIdentifier) *NullablePermissionIdentifier {
	return &NullablePermissionIdentifier{value: val, isSet: true}
}

func (v NullablePermissionIdentifier) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePermissionIdentifier) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


