/*
 * Relay API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: v20200615
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// Tokens A list of tokens
type Tokens struct {
	// A list of tokens
	Tokens *[]Token `json:"tokens,omitempty"`
}

// NewTokens instantiates a new Tokens object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTokens() *Tokens {
	this := Tokens{}
	return &this
}

// NewTokensWithDefaults instantiates a new Tokens object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTokensWithDefaults() *Tokens {
	this := Tokens{}
	return &this
}

// GetTokens returns the Tokens field value if set, zero value otherwise.
func (o *Tokens) GetTokens() []Token {
	if o == nil || o.Tokens == nil {
		var ret []Token
		return ret
	}
	return *o.Tokens
}

// GetTokensOk returns a tuple with the Tokens field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Tokens) GetTokensOk() (*[]Token, bool) {
	if o == nil || o.Tokens == nil {
		return nil, false
	}
	return o.Tokens, true
}

// HasTokens returns a boolean if a field has been set.
func (o *Tokens) HasTokens() bool {
	if o != nil && o.Tokens != nil {
		return true
	}

	return false
}

// SetTokens gets a reference to the given []Token and assigns it to the Tokens field.
func (o *Tokens) SetTokens(v []Token) {
	o.Tokens = &v
}

func (o Tokens) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Tokens != nil {
		toSerialize["tokens"] = o.Tokens
	}
	return json.Marshal(toSerialize)
}

type NullableTokens struct {
	value *Tokens
	isSet bool
}

func (v NullableTokens) Get() *Tokens {
	return v.value
}

func (v *NullableTokens) Set(val *Tokens) {
	v.value = val
	v.isSet = true
}

func (v NullableTokens) IsSet() bool {
	return v.isSet
}

func (v *NullableTokens) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTokens(val *Tokens) *NullableTokens {
	return &NullableTokens{value: val, isSet: true}
}

func (v NullableTokens) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTokens) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


