// Code generated by go-swagger; DO NOT EDIT.

package integrations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetIntegrationsParams creates a new GetIntegrationsParams object
// with the default values initialized.
func NewGetIntegrationsParams() *GetIntegrationsParams {

	return &GetIntegrationsParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetIntegrationsParamsWithTimeout creates a new GetIntegrationsParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetIntegrationsParamsWithTimeout(timeout time.Duration) *GetIntegrationsParams {

	return &GetIntegrationsParams{

		timeout: timeout,
	}
}

// NewGetIntegrationsParamsWithContext creates a new GetIntegrationsParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetIntegrationsParamsWithContext(ctx context.Context) *GetIntegrationsParams {

	return &GetIntegrationsParams{

		Context: ctx,
	}
}

// NewGetIntegrationsParamsWithHTTPClient creates a new GetIntegrationsParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetIntegrationsParamsWithHTTPClient(client *http.Client) *GetIntegrationsParams {

	return &GetIntegrationsParams{
		HTTPClient: client,
	}
}

/*GetIntegrationsParams contains all the parameters to send to the API endpoint
for the get integrations operation typically these are written to a http.Request
*/
type GetIntegrationsParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get integrations params
func (o *GetIntegrationsParams) WithTimeout(timeout time.Duration) *GetIntegrationsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get integrations params
func (o *GetIntegrationsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get integrations params
func (o *GetIntegrationsParams) WithContext(ctx context.Context) *GetIntegrationsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get integrations params
func (o *GetIntegrationsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get integrations params
func (o *GetIntegrationsParams) WithHTTPClient(client *http.Client) *GetIntegrationsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get integrations params
func (o *GetIntegrationsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *GetIntegrationsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
